### PR TITLE
include roboto font from google cdn and define on body css

### PR DESCRIPTION
**Pull request by mattadjohnson**
Fixes Issue #7 , also my editor decided to clean up a bunch of spacing and indentation issues it seems :stuck_out_tongue:

### CODE REVIEW

**Comment by adriangritz** [comment]
Is it possible for you to fix conflicts and re-submit pull-request?

I am glad this happened. If you run git config --global core.autocrlf what do you get? "input" or something else?

**Comment by mattadjohnson** [comment]
conflicts fixed. I ran that and nothing seemed to happen. I think it's more editor related, as when I switched to atom instead of sublime it's been auto cleaning up excess spaces and stuff. I can attempt to remove the space deletions from this PR if you want, but hey, free cleaning :stuck_out_tongue:

**Comment by adriangritz** [comment]
Sweet thanks! I have my core.autocrlf file set to "input". Next time I will create a .gitattributes file and set the default behavior for everyone. https://help.github.com/articles/dealing-with-line-endings/

**Comment by mattadjohnson** [comment]
yeah CRLFs can be a pain. I think everything that's changed in this PR is just deleting extra spaces at the end of lines, not the actual [Enter] key carriage return. i.e. `"Hello          "` vs `"Hello"`

**Comment by adriangritz** [comment]
Cool. Cool. Thanks for the help. Enjoy your time off!

**Pull request merged**
